name: Update and Publish

on:
  workflow_dispatch: {}
  push:
    branches:
      - main  # Change this to the default branch name if different

jobs:
  update_and_publish:
    runs-on: windows-latest  # Use the appropriate runner for PowerShell

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run PowerShell script
        run: powershell -File ./MoD_updater.ps1

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update files after processing

      # Use the secret token for authentication
      - name: Push Changes to GitHub
        run: |
          git config user.name "AlphaOmega2020"
          git config user.email "AlphaOmegaxUK@outlook.com"
          git add .
          git commit -m "Updated files"
          git push https://your-access-token@github.com/InsideEarth2150/MoDs.git HEAD:main
        env:
          MY_ACCESS_TOKEN: ${{ secrets.UPDATER_BOT_SECRET }}
